### ISSUE TITLE
Create RNN based Performance Indicators [5pt]

### ISSUE THREAD

**Issue by pacospace** [thoth-station/performance#54]
**Is your feature request related to a problem? Please describe.**
Thoth need to analyze the performance of RNN based algorithms

**Describe the solution you'd like**
Create RNN based Performance Indicator (e.g. LSTM layer)

**Describe alternatives you've considered**

**Additional context**

**Comment by fridex** [comment]
+1

It might be also good idea to check some model zoo and get models from there.

**Comment by goern** [comment]
@pacospace something we still want to work on?

**Comment by pacospace** [comment]
> @pacospace something we still want to work on?

yes I think so, also model zoo as @fridex suggested might be good to have a look.

/remove-lifecycle stale
